nodeLinker: node-modules

packageExtensions:
  '@commitlint/load@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  '@commitlint/cli@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
